"""Каталог событий Warehouse Device Server (имена для журнала и ручной инъекции)."""

from __future__ import annotations

SYSTEM_STARTED = "SYSTEM_STARTED"
SYSTEM_PAUSED = "SYSTEM_PAUSED"
SYSTEM_STOPPED = "SYSTEM_STOPPED"
SYSTEM_RESET = "SYSTEM_RESET"

TRUCK_ARRIVED = "TRUCK_ARRIVED"
TRUCK_DEPARTED = "TRUCK_DEPARTED"

RECEIVING_STARTED = "RECEIVING_STARTED"
ITEM_SCANNED = "ITEM_SCANNED"
ITEM_RECEIVED = "ITEM_RECEIVED"
ITEM_STORED = "ITEM_STORED"
ITEM_PICKED = "ITEM_PICKED"
ITEM_PACKED = "ITEM_PACKED"
ITEM_SHIPPED = "ITEM_SHIPPED"

ORDER_CREATED = "ORDER_CREATED"
ORDER_RELEASED = "ORDER_RELEASED"
PICKING_STARTED = "PICKING_STARTED"
PICKING_COMPLETED = "PICKING_COMPLETED"

TASK_CREATED = "TASK_CREATED"
TASK_ASSIGNED = "TASK_ASSIGNED"
TASK_STARTED = "TASK_STARTED"
TASK_COMPLETED = "TASK_COMPLETED"
TASK_FAILED = "TASK_FAILED"
TASK_BLOCKED = "TASK_BLOCKED"

DEVICE_ONLINE = "DEVICE_ONLINE"
DEVICE_OFFLINE = "DEVICE_OFFLINE"
DEVICE_STARTED = "DEVICE_STARTED"
DEVICE_STOPPED = "DEVICE_STOPPED"
DEVICE_MOVING = "DEVICE_MOVING"
DEVICE_IDLE = "DEVICE_IDLE"
DEVICE_ERROR = "DEVICE_ERROR"
DEVICE_RECOVERED = "DEVICE_RECOVERED"

AGV_BATTERY_LOW = "AGV_BATTERY_LOW"
AGV_CHARGING = "AGV_CHARGING"
AGV_CHARGED = "AGV_CHARGED"

CONVEYOR_STARTED = "CONVEYOR_STARTED"
CONVEYOR_STOPPED = "CONVEYOR_STOPPED"
CONVEYOR_BLOCKED = "CONVEYOR_BLOCKED"

ZONE_CONGESTED = "ZONE_CONGESTED"
ZONE_CLEARED = "ZONE_CLEARED"

EMERGENCY_STOP = "EMERGENCY_STOP"

SCAN_FAILED = "SCAN_FAILED"
SENSOR_ALARM = "SENSOR_ALARM"
SENSOR_READING = "SENSOR_READING"
STORAGE_FULL = "STORAGE_FULL"
WORKER_BREAK = "WORKER_BREAK"

CAMERA_ONLINE = "CAMERA_ONLINE"
CAMERA_OFFLINE = "CAMERA_OFFLINE"
OBJECT_DETECTED = "OBJECT_DETECTED"
PERSON_DETECTED = "PERSON_DETECTED"
PERSON_DETECTED_IN_PATH = "PERSON_DETECTED_IN_PATH"
OBSTACLE_DETECTED = "OBSTACLE_DETECTED"
CAMERA_DETECTION_CLEARED = "CAMERA_DETECTION_CLEARED"
CAMERA_OBJECT_DETECTED = "CAMERA_OBJECT_DETECTED"
CAMERA_OBJECT_LOST = "CAMERA_OBJECT_LOST"
CAMERA_PERSON_DETECTED = "CAMERA_PERSON_DETECTED"
CAMERA_OBSTACLE_DETECTED = "CAMERA_OBSTACLE_DETECTED"
CAMERA_OBSTACLE_CLEARED = "CAMERA_OBSTACLE_CLEARED"

# События, которые интеграционный слой проецирует на WMS-домен.
INTEGRATION_EVENT_TYPES: frozenset[str] = frozenset(
    {
        TRUCK_ARRIVED,
        TRUCK_DEPARTED,
        RECEIVING_STARTED,
        ITEM_RECEIVED,
        ITEM_STORED,
        ITEM_PICKED,
        ITEM_PACKED,
        ITEM_SHIPPED,
        ORDER_CREATED,
        ORDER_RELEASED,
        PICKING_STARTED,
        PICKING_COMPLETED,
        TASK_CREATED,
        TASK_ASSIGNED,
        TASK_STARTED,
        TASK_COMPLETED,
        TASK_FAILED,
        TASK_BLOCKED,
        DEVICE_ERROR,
        DEVICE_RECOVERED,
    }
)

ALL_EVENT_TYPES: tuple[str, ...] = (
    SYSTEM_STARTED,
    SYSTEM_PAUSED,
    SYSTEM_STOPPED,
    SYSTEM_RESET,
    TRUCK_ARRIVED,
    TRUCK_DEPARTED,
    RECEIVING_STARTED,
    ITEM_SCANNED,
    ITEM_RECEIVED,
    ITEM_STORED,
    ITEM_PICKED,
    ITEM_PACKED,
    ITEM_SHIPPED,
    ORDER_CREATED,
    ORDER_RELEASED,
    PICKING_STARTED,
    PICKING_COMPLETED,
    TASK_CREATED,
    TASK_ASSIGNED,
    TASK_STARTED,
    TASK_COMPLETED,
    TASK_FAILED,
    TASK_BLOCKED,
    DEVICE_ONLINE,
    DEVICE_OFFLINE,
    DEVICE_STARTED,
    DEVICE_STOPPED,
    DEVICE_MOVING,
    DEVICE_IDLE,
    DEVICE_ERROR,
    DEVICE_RECOVERED,
    AGV_BATTERY_LOW,
    AGV_CHARGING,
    AGV_CHARGED,
    CONVEYOR_STARTED,
    CONVEYOR_STOPPED,
    CONVEYOR_BLOCKED,
    ZONE_CONGESTED,
    ZONE_CLEARED,
    EMERGENCY_STOP,
    SCAN_FAILED,
    SENSOR_ALARM,
    SENSOR_READING,
    STORAGE_FULL,
    WORKER_BREAK,
    CAMERA_ONLINE,
    CAMERA_OFFLINE,
    OBJECT_DETECTED,
    PERSON_DETECTED,
    PERSON_DETECTED_IN_PATH,
    OBSTACLE_DETECTED,
    CAMERA_DETECTION_CLEARED,
    CAMERA_OBJECT_DETECTED,
    CAMERA_OBJECT_LOST,
    CAMERA_PERSON_DETECTED,
    CAMERA_OBSTACLE_DETECTED,
    CAMERA_OBSTACLE_CLEARED,
)

MANUAL_EVENT_TYPES: tuple[str, ...] = (
    AGV_BATTERY_LOW,
    CONVEYOR_BLOCKED,
    DEVICE_ERROR,
    EMERGENCY_STOP,
    ZONE_CONGESTED,
    SENSOR_ALARM,
)
