// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type CategoryCreate = {
  name: string
  parent_id?: string | null
}

export type CategoryPublic = {
  id: string
  name: string
  parent_id?: string | null
}

export type CategoryUpdate = {
  name?: string | null
  parent_id?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
  quantity?: number
  sku?: string | null
  barcode?: string | null
  unit?: string | null
  expires_at?: string | null
  location?: string | null
  category_id?: string | null
  storage_row?: number | null
  storage_level?: number | null
  storage_cell_x?: number | null
  storage_cell_z?: number | null
}

export type ItemHistoryList = {
  data: Array<ItemHistoryPublic>
  count: number
}

export type ItemHistoryPublic = {
  id: string
  item_id: string
  user_id: string
  changed_at: string
  field_name: string
  old_value: string
  new_value: string
}

export type ItemPublic = {
  title: string
  description?: string | null
  quantity?: number
  sku?: string | null
  barcode?: string | null
  unit?: string | null
  expires_at?: string | null
  location?: string | null
  id: string
  owner_id: string
  status: string
  category_id?: string | null
  created_at: string
  storage_row?: number | null
  storage_level?: number | null
  storage_cell_x?: number | null
  storage_cell_z?: number | null
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
  quantity?: number | null
  sku?: string | null
  barcode?: string | null
  unit?: string | null
  expires_at?: string | null
  location?: string | null
  storage_row?: number | null
  storage_level?: number | null
  storage_cell_x?: number | null
  storage_cell_z?: number | null
  status?: string | null
  category_id?: string | null
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type RolePublic = {
  id: string
  name: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
  role_id?: string | null
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
  role_id?: string | null
  last_login_at?: string | null
  deleted_at?: string | null
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
  role_id?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type CategoriesReadCategoriesResponse = Array<CategoryPublic>

export type CategoriesCreateCategoryData = {
  requestBody: CategoryCreate
}

export type CategoriesCreateCategoryResponse = CategoryPublic

export type CategoriesReadCategoryData = {
  id: string
}

export type CategoriesReadCategoryResponse = CategoryPublic

export type CategoriesUpdateCategoryData = {
  id: string
  requestBody: CategoryUpdate
}

export type CategoriesUpdateCategoryResponse = CategoryPublic

export type CategoriesDeleteCategoryData = {
  id: string
}

export type CategoriesDeleteCategoryResponse = Message

export type DashboardGetDashboardStatsResponse = {
  [key: string]: unknown
}

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
  status?: string | null
  search?: string | null
  category_id?: string | null
  created_at_from?: string | null
  created_at_to?: string | null
  sort_by?: string | null
  sort_order?: string | null
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemHistoryData = {
  id: string
}

export type ItemsReadItemHistoryResponse = ItemHistoryList

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type UsersReadUsersData = {
  limit?: number
  skip?: number
  deleted?: boolean
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UsersRestoreUserData = {
  userId: string
}

export type UsersRestoreUserResponse = UserPublic

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
