"""Warehouse Device Server tables (wsim_*).

Revision ID: a9b0c1d2e3f4
Revises: d1e2f3a4b5c6
Create Date: 2026-09-15

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, UUID

revision = "a9b0c1d2e3f4"
down_revision = "d1e2f3a4b5c6"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "wsim_warehouse",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("width_m", sa.Float(), nullable=False),
        sa.Column("height_m", sa.Float(), nullable=False),
        sa.Column("grid_cell_m", sa.Float(), nullable=False, server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "wsim_zone",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("warehouse_id", UUID(as_uuid=True), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("zone_type", sa.String(length=32), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=False, server_default="#3b82f6"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["warehouse_id"], ["wsim_warehouse.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_id", "code", name="uq_wsim_zone_wh_code"),
    )
    op.create_index("ix_wsim_zone_warehouse_id", "wsim_zone", ["warehouse_id"])
    op.create_table(
        "wsim_aisle",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("warehouse_id", UUID(as_uuid=True), nullable=False),
        sa.Column("zone_id", UUID(as_uuid=True), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("orientation", sa.String(length=16), nullable=False),
        sa.Column("axis_coord", sa.Float(), nullable=False),
        sa.Column("from_coord", sa.Float(), nullable=False),
        sa.Column("to_coord", sa.Float(), nullable=False),
        sa.Column("width_m", sa.Float(), nullable=False, server_default="2.5"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["warehouse_id"], ["wsim_warehouse.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["zone_id"], ["wsim_zone.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_id", "code", name="uq_wsim_aisle_wh_code"),
    )
    op.create_table(
        "wsim_rack",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("warehouse_id", UUID(as_uuid=True), nullable=False),
        sa.Column("zone_id", UUID(as_uuid=True), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("bays", sa.Integer(), nullable=False),
        sa.Column("levels", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["warehouse_id"], ["wsim_warehouse.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["zone_id"], ["wsim_zone.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_id", "code", name="uq_wsim_rack_wh_code"),
    )
    op.create_table(
        "wsim_storage_location",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("warehouse_id", UUID(as_uuid=True), nullable=False),
        sa.Column("rack_id", UUID(as_uuid=True), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("bay", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("occupied", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("approach_x", sa.Float(), nullable=False),
        sa.Column("approach_y", sa.Float(), nullable=False),
        sa.Column("blocked", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["warehouse_id"], ["wsim_warehouse.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rack_id"], ["wsim_rack.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_id", "code", name="uq_wsim_storage_location_wh_code"),
    )
    op.create_table(
        "wsim_dock",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("warehouse_id", UUID(as_uuid=True), nullable=False),
        sa.Column("zone_id", UUID(as_uuid=True), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("dock_type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="FREE"),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("yard_x", sa.Float(), nullable=False),
        sa.Column("yard_y", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["warehouse_id"], ["wsim_warehouse.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["zone_id"], ["wsim_zone.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_id", "code", name="uq_wsim_dock_wh_code"),
    )
    op.create_table(
        "wsim_device",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("warehouse_id", UUID(as_uuid=True), nullable=False),
        sa.Column("zone_id", UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("device_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="IDLE"),
        sa.Column("battery", sa.Float(), nullable=True),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("home_x", sa.Float(), nullable=False),
        sa.Column("home_y", sa.Float(), nullable=False),
        sa.Column("speed_mps", sa.Float(), nullable=False, server_default="0"),
        sa.Column("current_task_id", UUID(as_uuid=True), nullable=True),
        sa.Column("meta", JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["warehouse_id"], ["wsim_warehouse.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["zone_id"], ["wsim_zone.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_id", "name", name="uq_wsim_device_wh_name"),
    )
    op.create_index("ix_wsim_device_device_type", "wsim_device", ["device_type"])
    op.create_table(
        "wsim_product",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False, server_default="шт"),
        sa.Column("units_per_pallet", sa.Integer(), nullable=False, server_default="100"),
        sa.Column("cold_chain", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku"),
    )
    op.create_table(
        "wsim_inventory_item",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("warehouse_id", UUID(as_uuid=True), nullable=False),
        sa.Column("product_id", UUID(as_uuid=True), nullable=False),
        sa.Column("lpn", sa.String(length=64), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="RECEIVED"),
        sa.Column("location_kind", sa.String(length=24), nullable=False, server_default="ZONE"),
        sa.Column("storage_location_id", UUID(as_uuid=True), nullable=True),
        sa.Column("zone_id", UUID(as_uuid=True), nullable=True),
        sa.Column("device_id", UUID(as_uuid=True), nullable=True),
        sa.Column("truck_id", UUID(as_uuid=True), nullable=True),
        sa.Column("order_id", UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["warehouse_id"], ["wsim_warehouse.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["wsim_product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["storage_location_id"], ["wsim_storage_location.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["zone_id"], ["wsim_zone.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lpn"),
    )
    op.create_table(
        "wsim_inventory_movement",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("warehouse_id", UUID(as_uuid=True), nullable=False),
        sa.Column("inventory_item_id", UUID(as_uuid=True), nullable=False),
        sa.Column("product_id", UUID(as_uuid=True), nullable=False),
        sa.Column("movement_type", sa.String(length=16), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("from_kind", sa.String(length=24), nullable=True),
        sa.Column("from_id", UUID(as_uuid=True), nullable=True),
        sa.Column("from_label", sa.String(length=128), nullable=True),
        sa.Column("to_kind", sa.String(length=24), nullable=True),
        sa.Column("to_id", UUID(as_uuid=True), nullable=True),
        sa.Column("to_label", sa.String(length=128), nullable=True),
        sa.Column("task_id", UUID(as_uuid=True), nullable=True),
        sa.Column("sim_time_sec", sa.Float(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["warehouse_id"], ["wsim_warehouse.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["inventory_item_id"], ["wsim_inventory_item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["wsim_product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wsim_truck",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("warehouse_id", UUID(as_uuid=True), nullable=False),
        sa.Column("plate", sa.String(length=32), nullable=False),
        sa.Column("carrier", sa.String(length=128), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="QUEUED"),
        sa.Column("dock_id", UUID(as_uuid=True), nullable=True),
        sa.Column("pallets_planned", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("pallets_done", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("x", sa.Float(), nullable=False, server_default="0"),
        sa.Column("y", sa.Float(), nullable=False, server_default="0"),
        sa.Column("arrived_sim_sec", sa.Float(), nullable=False, server_default="0"),
        sa.Column("departed_sim_sec", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["warehouse_id"], ["wsim_warehouse.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["dock_id"], ["wsim_dock.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wsim_order",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("warehouse_id", UUID(as_uuid=True), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="CREATED"),
        sa.Column("priority", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("counterparty", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("truck_id", UUID(as_uuid=True), nullable=True),
        sa.Column("created_sim_sec", sa.Float(), nullable=False, server_default="0"),
        sa.Column("due_sim_sec", sa.Float(), nullable=True),
        sa.Column("released_sim_sec", sa.Float(), nullable=True),
        sa.Column("completed_sim_sec", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["warehouse_id"], ["wsim_warehouse.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["truck_id"], ["wsim_truck.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_id", "code", name="uq_wsim_order_wh_code"),
    )
    op.create_table(
        "wsim_order_item",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("order_id", UUID(as_uuid=True), nullable=False),
        sa.Column("product_id", UUID(as_uuid=True), nullable=False),
        sa.Column("qty_ordered", sa.Integer(), nullable=False),
        sa.Column("qty_received", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("qty_picked", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("qty_packed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("qty_shipped", sa.Integer(), nullable=False, server_default="0"),
        sa.ForeignKeyConstraint(["order_id"], ["wsim_order.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["wsim_product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wsim_task",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("warehouse_id", UUID(as_uuid=True), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("task_type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="CREATED"),
        sa.Column("priority", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("source_kind", sa.String(length=24), nullable=True),
        sa.Column("source_id", UUID(as_uuid=True), nullable=True),
        sa.Column("source_label", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("source_x", sa.Float(), nullable=False, server_default="0"),
        sa.Column("source_y", sa.Float(), nullable=False, server_default="0"),
        sa.Column("dest_kind", sa.String(length=24), nullable=True),
        sa.Column("dest_id", UUID(as_uuid=True), nullable=True),
        sa.Column("dest_label", sa.String(length=128), nullable=False, server_default=""),
        sa.Column("dest_x", sa.Float(), nullable=False, server_default="0"),
        sa.Column("dest_y", sa.Float(), nullable=False, server_default="0"),
        sa.Column("assigned_device_id", UUID(as_uuid=True), nullable=True),
        sa.Column("order_id", UUID(as_uuid=True), nullable=True),
        sa.Column("inventory_item_id", UUID(as_uuid=True), nullable=True),
        sa.Column("storage_location_id", UUID(as_uuid=True), nullable=True),
        sa.Column("blocked_reason", sa.String(length=255), nullable=True),
        sa.Column("payload", JSONB(), nullable=True),
        sa.Column("created_sim_sec", sa.Float(), nullable=False, server_default="0"),
        sa.Column("started_sim_sec", sa.Float(), nullable=True),
        sa.Column("completed_sim_sec", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["warehouse_id"], ["wsim_warehouse.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["assigned_device_id"], ["wsim_device.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["wsim_order.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["inventory_item_id"], ["wsim_inventory_item.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["storage_location_id"], ["wsim_storage_location.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wsim_event",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_id", UUID(as_uuid=True), nullable=True),
        sa.Column("run_id", UUID(as_uuid=True), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sim_time_sec", sa.Float(), nullable=False, server_default="0"),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False, server_default="INFO"),
        sa.Column("message", sa.String(length=512), nullable=False),
        sa.Column("device_id", UUID(as_uuid=True), nullable=True),
        sa.Column("task_id", UUID(as_uuid=True), nullable=True),
        sa.Column("order_id", UUID(as_uuid=True), nullable=True),
        sa.Column("product_id", UUID(as_uuid=True), nullable=True),
        sa.Column("zone_id", UUID(as_uuid=True), nullable=True),
        sa.Column("payload", JSONB(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_wsim_event_seq", "wsim_event", ["seq"])
    op.create_index("ix_wsim_event_event_type", "wsim_event", ["event_type"])
    op.create_table(
        "wsim_scenario",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False, server_default=""),
        sa.Column("config", JSONB(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "wsim_run",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("warehouse_id", UUID(as_uuid=True), nullable=False),
        sa.Column("scenario_id", UUID(as_uuid=True), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False, server_default="STOPPED"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("speed", sa.Float(), nullable=False, server_default="1"),
        sa.Column("sim_time_sec", sa.Float(), nullable=False, server_default="0"),
        sa.Column("day_start_sec", sa.Float(), nullable=False, server_default="28800"),
        sa.Column("event_seq", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("config", JSONB(), nullable=False),
        sa.Column("kpi", JSONB(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["warehouse_id"], ["wsim_warehouse.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scenario_id"], ["wsim_scenario.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade():
    for table in (
        "wsim_run",
        "wsim_scenario",
        "wsim_event",
        "wsim_task",
        "wsim_order_item",
        "wsim_order",
        "wsim_truck",
        "wsim_inventory_movement",
        "wsim_inventory_item",
        "wsim_product",
        "wsim_device",
        "wsim_dock",
        "wsim_storage_location",
        "wsim_rack",
        "wsim_aisle",
        "wsim_zone",
        "wsim_warehouse",
    ):
        op.drop_table(table)
