/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWarehouse3dRouteImport } from './routes/_layout/warehouse-3d'
import { Route as LayoutWarehouseRouteImport } from './routes/_layout/warehouse'
import { Route as LayoutTechniqueRouteImport } from './routes/_layout/technique'
import { Route as LayoutShippedRouteImport } from './routes/_layout/shipped'
import { Route as LayoutShipmentRouteImport } from './routes/_layout/shipment'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutTechniqueIndexRouteImport } from './routes/_layout/technique/index'
import { Route as LayoutTechniqueEquipmentNewRouteImport } from './routes/_layout/technique/equipment.new'
import { Route as LayoutTechniqueEquipmentEquipmentIdRouteImport } from './routes/_layout/technique/equipment.$equipmentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWarehouse3dRoute = LayoutWarehouse3dRouteImport.update({
  id: '/warehouse-3d',
  path: '/warehouse-3d',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWarehouseRoute = LayoutWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTechniqueRoute = LayoutTechniqueRouteImport.update({
  id: '/technique',
  path: '/technique',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShippedRoute = LayoutShippedRouteImport.update({
  id: '/shipped',
  path: '/shipped',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShipmentRoute = LayoutShipmentRouteImport.update({
  id: '/shipment',
  path: '/shipment',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTechniqueIndexRoute = LayoutTechniqueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTechniqueRoute,
} as any)
const LayoutTechniqueEquipmentNewRoute =
  LayoutTechniqueEquipmentNewRouteImport.update({
    id: '/equipment/new',
    path: '/equipment/new',
    getParentRoute: () => LayoutTechniqueRoute,
  } as any)
const LayoutTechniqueEquipmentEquipmentIdRoute =
  LayoutTechniqueEquipmentEquipmentIdRouteImport.update({
    id: '/equipment/$equipmentId',
    path: '/equipment/$equipmentId',
    getParentRoute: () => LayoutTechniqueRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/shipment': typeof LayoutShipmentRoute
  '/shipped': typeof LayoutShippedRoute
  '/technique': typeof LayoutTechniqueRouteWithChildren
  '/warehouse': typeof LayoutWarehouseRoute
  '/warehouse-3d': typeof LayoutWarehouse3dRoute
  '/technique/': typeof LayoutTechniqueIndexRoute
  '/technique/equipment/$equipmentId': typeof LayoutTechniqueEquipmentEquipmentIdRoute
  '/technique/equipment/new': typeof LayoutTechniqueEquipmentNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/shipment': typeof LayoutShipmentRoute
  '/shipped': typeof LayoutShippedRoute
  '/warehouse': typeof LayoutWarehouseRoute
  '/warehouse-3d': typeof LayoutWarehouse3dRoute
  '/': typeof LayoutIndexRoute
  '/technique': typeof LayoutTechniqueIndexRoute
  '/technique/equipment/$equipmentId': typeof LayoutTechniqueEquipmentEquipmentIdRoute
  '/technique/equipment/new': typeof LayoutTechniqueEquipmentNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/shipment': typeof LayoutShipmentRoute
  '/_layout/shipped': typeof LayoutShippedRoute
  '/_layout/technique': typeof LayoutTechniqueRouteWithChildren
  '/_layout/warehouse': typeof LayoutWarehouseRoute
  '/_layout/warehouse-3d': typeof LayoutWarehouse3dRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/technique/': typeof LayoutTechniqueIndexRoute
  '/_layout/technique/equipment/$equipmentId': typeof LayoutTechniqueEquipmentEquipmentIdRoute
  '/_layout/technique/equipment/new': typeof LayoutTechniqueEquipmentNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/items'
    | '/settings'
    | '/shipment'
    | '/shipped'
    | '/technique'
    | '/warehouse'
    | '/warehouse-3d'
    | '/technique/'
    | '/technique/equipment/$equipmentId'
    | '/technique/equipment/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/items'
    | '/settings'
    | '/shipment'
    | '/shipped'
    | '/warehouse'
    | '/warehouse-3d'
    | '/'
    | '/technique'
    | '/technique/equipment/$equipmentId'
    | '/technique/equipment/new'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/dashboard'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/shipment'
    | '/_layout/shipped'
    | '/_layout/technique'
    | '/_layout/warehouse'
    | '/_layout/warehouse-3d'
    | '/_layout/'
    | '/_layout/technique/'
    | '/_layout/technique/equipment/$equipmentId'
    | '/_layout/technique/equipment/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/warehouse-3d': {
      id: '/_layout/warehouse-3d'
      path: '/warehouse-3d'
      fullPath: '/warehouse-3d'
      preLoaderRoute: typeof LayoutWarehouse3dRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/warehouse': {
      id: '/_layout/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof LayoutWarehouseRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/technique': {
      id: '/_layout/technique'
      path: '/technique'
      fullPath: '/technique'
      preLoaderRoute: typeof LayoutTechniqueRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shipped': {
      id: '/_layout/shipped'
      path: '/shipped'
      fullPath: '/shipped'
      preLoaderRoute: typeof LayoutShippedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shipment': {
      id: '/_layout/shipment'
      path: '/shipment'
      fullPath: '/shipment'
      preLoaderRoute: typeof LayoutShipmentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/technique/': {
      id: '/_layout/technique/'
      path: '/'
      fullPath: '/technique/'
      preLoaderRoute: typeof LayoutTechniqueIndexRouteImport
      parentRoute: typeof LayoutTechniqueRoute
    }
    '/_layout/technique/equipment/new': {
      id: '/_layout/technique/equipment/new'
      path: '/equipment/new'
      fullPath: '/technique/equipment/new'
      preLoaderRoute: typeof LayoutTechniqueEquipmentNewRouteImport
      parentRoute: typeof LayoutTechniqueRoute
    }
    '/_layout/technique/equipment/$equipmentId': {
      id: '/_layout/technique/equipment/$equipmentId'
      path: '/equipment/$equipmentId'
      fullPath: '/technique/equipment/$equipmentId'
      preLoaderRoute: typeof LayoutTechniqueEquipmentEquipmentIdRouteImport
      parentRoute: typeof LayoutTechniqueRoute
    }
  }
}

interface LayoutTechniqueRouteChildren {
  LayoutTechniqueIndexRoute: typeof LayoutTechniqueIndexRoute
  LayoutTechniqueEquipmentEquipmentIdRoute: typeof LayoutTechniqueEquipmentEquipmentIdRoute
  LayoutTechniqueEquipmentNewRoute: typeof LayoutTechniqueEquipmentNewRoute
}

const LayoutTechniqueRouteChildren: LayoutTechniqueRouteChildren = {
  LayoutTechniqueIndexRoute: LayoutTechniqueIndexRoute,
  LayoutTechniqueEquipmentEquipmentIdRoute:
    LayoutTechniqueEquipmentEquipmentIdRoute,
  LayoutTechniqueEquipmentNewRoute: LayoutTechniqueEquipmentNewRoute,
}

const LayoutTechniqueRouteWithChildren = LayoutTechniqueRoute._addFileChildren(
  LayoutTechniqueRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutShipmentRoute: typeof LayoutShipmentRoute
  LayoutShippedRoute: typeof LayoutShippedRoute
  LayoutTechniqueRoute: typeof LayoutTechniqueRouteWithChildren
  LayoutWarehouseRoute: typeof LayoutWarehouseRoute
  LayoutWarehouse3dRoute: typeof LayoutWarehouse3dRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutShipmentRoute: LayoutShipmentRoute,
  LayoutShippedRoute: LayoutShippedRoute,
  LayoutTechniqueRoute: LayoutTechniqueRouteWithChildren,
  LayoutWarehouseRoute: LayoutWarehouseRoute,
  LayoutWarehouse3dRoute: LayoutWarehouse3dRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
