/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutWarehouse3dImport } from './routes/_layout/warehouse-3d'
import { Route as LayoutWarehouseImport } from './routes/_layout/warehouse'
import { Route as LayoutTechniqueImport } from './routes/_layout/technique'
import { Route as LayoutShippedImport } from './routes/_layout/shipped'
import { Route as LayoutShipmentImport } from './routes/_layout/shipment'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutDashboardImport } from './routes/_layout/dashboard'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutTechniqueIndexImport } from './routes/_layout/technique/index'
import { Route as LayoutTechniqueEquipmentEquipmentIdImport } from './routes/_layout/technique/equipment.$equipmentId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutWarehouse3dRoute = LayoutWarehouse3dImport.update({
  path: '/warehouse-3d',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutWarehouseRoute = LayoutWarehouseImport.update({
  path: '/warehouse',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTechniqueRoute = LayoutTechniqueImport.update({
  path: '/technique',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutShippedRoute = LayoutShippedImport.update({
  path: '/shipped',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutShipmentRoute = LayoutShipmentImport.update({
  path: '/shipment',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRoute = LayoutDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTechniqueIndexRoute = LayoutTechniqueIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutTechniqueRoute,
} as any)

const LayoutTechniqueEquipmentEquipmentIdRoute =
  LayoutTechniqueEquipmentEquipmentIdImport.update({
    path: '/equipment/$equipmentId',
    getParentRoute: () => LayoutTechniqueRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard': {
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/shipment': {
      preLoaderRoute: typeof LayoutShipmentImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/shipped': {
      preLoaderRoute: typeof LayoutShippedImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/technique': {
      preLoaderRoute: typeof LayoutTechniqueImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/warehouse': {
      preLoaderRoute: typeof LayoutWarehouseImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/warehouse-3d': {
      preLoaderRoute: typeof LayoutWarehouse3dImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/technique/': {
      preLoaderRoute: typeof LayoutTechniqueIndexImport
      parentRoute: typeof LayoutTechniqueImport
    }
    '/_layout/technique/equipment/$equipmentId': {
      preLoaderRoute: typeof LayoutTechniqueEquipmentEquipmentIdImport
      parentRoute: typeof LayoutTechniqueImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutDashboardRoute,
    LayoutItemsRoute,
    LayoutSettingsRoute,
    LayoutShipmentRoute,
    LayoutShippedRoute,
    LayoutTechniqueRoute.addChildren([
      LayoutTechniqueIndexRoute,
      LayoutTechniqueEquipmentEquipmentIdRoute,
    ]),
    LayoutWarehouseRoute,
    LayoutWarehouse3dRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
