/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWarehouseTwinRouteImport } from './routes/_layout/warehouse-twin'
import { Route as LayoutWarehouseTasksRouteImport } from './routes/_layout/warehouse-tasks'
import { Route as LayoutWarehouseSimulationRouteImport } from './routes/_layout/warehouse-simulation'
import { Route as LayoutWarehouse3dHelpRouteImport } from './routes/_layout/warehouse-3d-help'
import { Route as LayoutWarehouse3dRouteImport } from './routes/_layout/warehouse-3d'
import { Route as LayoutWarehouseRouteImport } from './routes/_layout/warehouse'
import { Route as LayoutShippedRouteImport } from './routes/_layout/shipped'
import { Route as LayoutShipmentRouteImport } from './routes/_layout/shipment'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutOutboundOrdersRouteImport } from './routes/_layout/outbound-orders'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutInboundOrdersRouteImport } from './routes/_layout/inbound-orders'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutControlTowerRouteImport } from './routes/_layout/control-tower'
import { Route as LayoutAssistantRouteImport } from './routes/_layout/assistant'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutTechniqueRouteRouteImport } from './routes/_layout/technique/route'
import { Route as LayoutTechniqueIndexRouteImport } from './routes/_layout/technique/index'
import { Route as LayoutTechniqueWorkOrdersRouteImport } from './routes/_layout/technique/work-orders'
import { Route as LayoutTechniqueTechniciansRouteImport } from './routes/_layout/technique/technicians'
import { Route as LayoutTechniqueSparePartsRouteImport } from './routes/_layout/technique/spare-parts'
import { Route as LayoutTechniqueSecurityRouteImport } from './routes/_layout/technique/security'
import { Route as LayoutTechniquePredictiveRouteImport } from './routes/_layout/technique/predictive'
import { Route as LayoutTechniqueMaintenanceSettingsRouteImport } from './routes/_layout/technique/maintenance-settings'
import { Route as LayoutTechniqueMaintenanceScheduleRouteImport } from './routes/_layout/technique/maintenance-schedule'
import { Route as LayoutTechniqueMaintenanceRouteImport } from './routes/_layout/technique/maintenance'
import { Route as LayoutTechniqueIntegrationsRouteImport } from './routes/_layout/technique/integrations'
import { Route as LayoutTechniqueAnalyticsRouteImport } from './routes/_layout/technique/analytics'
import { Route as LayoutTechniqueAlertsRouteImport } from './routes/_layout/technique/alerts'
import { Route as LayoutTechniqueEquipmentNewRouteImport } from './routes/_layout/technique/equipment.new'
import { Route as LayoutTechniqueEquipmentEquipmentIdRouteImport } from './routes/_layout/technique/equipment.$equipmentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWarehouseTwinRoute = LayoutWarehouseTwinRouteImport.update({
  id: '/warehouse-twin',
  path: '/warehouse-twin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWarehouseTasksRoute = LayoutWarehouseTasksRouteImport.update({
  id: '/warehouse-tasks',
  path: '/warehouse-tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWarehouseSimulationRoute =
  LayoutWarehouseSimulationRouteImport.update({
    id: '/warehouse-simulation',
    path: '/warehouse-simulation',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutWarehouse3dHelpRoute = LayoutWarehouse3dHelpRouteImport.update({
  id: '/warehouse-3d-help',
  path: '/warehouse-3d-help',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWarehouse3dRoute = LayoutWarehouse3dRouteImport.update({
  id: '/warehouse-3d',
  path: '/warehouse-3d',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWarehouseRoute = LayoutWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShippedRoute = LayoutShippedRouteImport.update({
  id: '/shipped',
  path: '/shipped',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShipmentRoute = LayoutShipmentRouteImport.update({
  id: '/shipment',
  path: '/shipment',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOutboundOrdersRoute = LayoutOutboundOrdersRouteImport.update({
  id: '/outbound-orders',
  path: '/outbound-orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInboundOrdersRoute = LayoutInboundOrdersRouteImport.update({
  id: '/inbound-orders',
  path: '/inbound-orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutControlTowerRoute = LayoutControlTowerRouteImport.update({
  id: '/control-tower',
  path: '/control-tower',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAssistantRoute = LayoutAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTechniqueRouteRoute = LayoutTechniqueRouteRouteImport.update({
  id: '/technique',
  path: '/technique',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTechniqueIndexRoute = LayoutTechniqueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTechniqueRouteRoute,
} as any)
const LayoutTechniqueWorkOrdersRoute =
  LayoutTechniqueWorkOrdersRouteImport.update({
    id: '/work-orders',
    path: '/work-orders',
    getParentRoute: () => LayoutTechniqueRouteRoute,
  } as any)
const LayoutTechniqueTechniciansRoute =
  LayoutTechniqueTechniciansRouteImport.update({
    id: '/technicians',
    path: '/technicians',
    getParentRoute: () => LayoutTechniqueRouteRoute,
  } as any)
const LayoutTechniqueSparePartsRoute =
  LayoutTechniqueSparePartsRouteImport.update({
    id: '/spare-parts',
    path: '/spare-parts',
    getParentRoute: () => LayoutTechniqueRouteRoute,
  } as any)
const LayoutTechniqueSecurityRoute = LayoutTechniqueSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => LayoutTechniqueRouteRoute,
} as any)
const LayoutTechniquePredictiveRoute =
  LayoutTechniquePredictiveRouteImport.update({
    id: '/predictive',
    path: '/predictive',
    getParentRoute: () => LayoutTechniqueRouteRoute,
  } as any)
const LayoutTechniqueMaintenanceSettingsRoute =
  LayoutTechniqueMaintenanceSettingsRouteImport.update({
    id: '/maintenance-settings',
    path: '/maintenance-settings',
    getParentRoute: () => LayoutTechniqueRouteRoute,
  } as any)
const LayoutTechniqueMaintenanceScheduleRoute =
  LayoutTechniqueMaintenanceScheduleRouteImport.update({
    id: '/maintenance-schedule',
    path: '/maintenance-schedule',
    getParentRoute: () => LayoutTechniqueRouteRoute,
  } as any)
const LayoutTechniqueMaintenanceRoute =
  LayoutTechniqueMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => LayoutTechniqueRouteRoute,
  } as any)
const LayoutTechniqueIntegrationsRoute =
  LayoutTechniqueIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => LayoutTechniqueRouteRoute,
  } as any)
const LayoutTechniqueAnalyticsRoute =
  LayoutTechniqueAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => LayoutTechniqueRouteRoute,
  } as any)
const LayoutTechniqueAlertsRoute = LayoutTechniqueAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => LayoutTechniqueRouteRoute,
} as any)
const LayoutTechniqueEquipmentNewRoute =
  LayoutTechniqueEquipmentNewRouteImport.update({
    id: '/equipment/new',
    path: '/equipment/new',
    getParentRoute: () => LayoutTechniqueRouteRoute,
  } as any)
const LayoutTechniqueEquipmentEquipmentIdRoute =
  LayoutTechniqueEquipmentEquipmentIdRouteImport.update({
    id: '/equipment/$equipmentId',
    path: '/equipment/$equipmentId',
    getParentRoute: () => LayoutTechniqueRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/technique': typeof LayoutTechniqueRouteRouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/assistant': typeof LayoutAssistantRoute
  '/control-tower': typeof LayoutControlTowerRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/inbound-orders': typeof LayoutInboundOrdersRoute
  '/items': typeof LayoutItemsRoute
  '/outbound-orders': typeof LayoutOutboundOrdersRoute
  '/settings': typeof LayoutSettingsRoute
  '/shipment': typeof LayoutShipmentRoute
  '/shipped': typeof LayoutShippedRoute
  '/warehouse': typeof LayoutWarehouseRoute
  '/warehouse-3d': typeof LayoutWarehouse3dRoute
  '/warehouse-3d-help': typeof LayoutWarehouse3dHelpRoute
  '/warehouse-simulation': typeof LayoutWarehouseSimulationRoute
  '/warehouse-tasks': typeof LayoutWarehouseTasksRoute
  '/warehouse-twin': typeof LayoutWarehouseTwinRoute
  '/technique/alerts': typeof LayoutTechniqueAlertsRoute
  '/technique/analytics': typeof LayoutTechniqueAnalyticsRoute
  '/technique/integrations': typeof LayoutTechniqueIntegrationsRoute
  '/technique/maintenance': typeof LayoutTechniqueMaintenanceRoute
  '/technique/maintenance-schedule': typeof LayoutTechniqueMaintenanceScheduleRoute
  '/technique/maintenance-settings': typeof LayoutTechniqueMaintenanceSettingsRoute
  '/technique/predictive': typeof LayoutTechniquePredictiveRoute
  '/technique/security': typeof LayoutTechniqueSecurityRoute
  '/technique/spare-parts': typeof LayoutTechniqueSparePartsRoute
  '/technique/technicians': typeof LayoutTechniqueTechniciansRoute
  '/technique/work-orders': typeof LayoutTechniqueWorkOrdersRoute
  '/technique/': typeof LayoutTechniqueIndexRoute
  '/technique/equipment/$equipmentId': typeof LayoutTechniqueEquipmentEquipmentIdRoute
  '/technique/equipment/new': typeof LayoutTechniqueEquipmentNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/assistant': typeof LayoutAssistantRoute
  '/control-tower': typeof LayoutControlTowerRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/inbound-orders': typeof LayoutInboundOrdersRoute
  '/items': typeof LayoutItemsRoute
  '/outbound-orders': typeof LayoutOutboundOrdersRoute
  '/settings': typeof LayoutSettingsRoute
  '/shipment': typeof LayoutShipmentRoute
  '/shipped': typeof LayoutShippedRoute
  '/warehouse': typeof LayoutWarehouseRoute
  '/warehouse-3d': typeof LayoutWarehouse3dRoute
  '/warehouse-3d-help': typeof LayoutWarehouse3dHelpRoute
  '/warehouse-simulation': typeof LayoutWarehouseSimulationRoute
  '/warehouse-tasks': typeof LayoutWarehouseTasksRoute
  '/warehouse-twin': typeof LayoutWarehouseTwinRoute
  '/': typeof LayoutIndexRoute
  '/technique/alerts': typeof LayoutTechniqueAlertsRoute
  '/technique/analytics': typeof LayoutTechniqueAnalyticsRoute
  '/technique/integrations': typeof LayoutTechniqueIntegrationsRoute
  '/technique/maintenance': typeof LayoutTechniqueMaintenanceRoute
  '/technique/maintenance-schedule': typeof LayoutTechniqueMaintenanceScheduleRoute
  '/technique/maintenance-settings': typeof LayoutTechniqueMaintenanceSettingsRoute
  '/technique/predictive': typeof LayoutTechniquePredictiveRoute
  '/technique/security': typeof LayoutTechniqueSecurityRoute
  '/technique/spare-parts': typeof LayoutTechniqueSparePartsRoute
  '/technique/technicians': typeof LayoutTechniqueTechniciansRoute
  '/technique/work-orders': typeof LayoutTechniqueWorkOrdersRoute
  '/technique': typeof LayoutTechniqueIndexRoute
  '/technique/equipment/$equipmentId': typeof LayoutTechniqueEquipmentEquipmentIdRoute
  '/technique/equipment/new': typeof LayoutTechniqueEquipmentNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/technique': typeof LayoutTechniqueRouteRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/assistant': typeof LayoutAssistantRoute
  '/_layout/control-tower': typeof LayoutControlTowerRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/inbound-orders': typeof LayoutInboundOrdersRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/outbound-orders': typeof LayoutOutboundOrdersRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/shipment': typeof LayoutShipmentRoute
  '/_layout/shipped': typeof LayoutShippedRoute
  '/_layout/warehouse': typeof LayoutWarehouseRoute
  '/_layout/warehouse-3d': typeof LayoutWarehouse3dRoute
  '/_layout/warehouse-3d-help': typeof LayoutWarehouse3dHelpRoute
  '/_layout/warehouse-simulation': typeof LayoutWarehouseSimulationRoute
  '/_layout/warehouse-tasks': typeof LayoutWarehouseTasksRoute
  '/_layout/warehouse-twin': typeof LayoutWarehouseTwinRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/technique/alerts': typeof LayoutTechniqueAlertsRoute
  '/_layout/technique/analytics': typeof LayoutTechniqueAnalyticsRoute
  '/_layout/technique/integrations': typeof LayoutTechniqueIntegrationsRoute
  '/_layout/technique/maintenance': typeof LayoutTechniqueMaintenanceRoute
  '/_layout/technique/maintenance-schedule': typeof LayoutTechniqueMaintenanceScheduleRoute
  '/_layout/technique/maintenance-settings': typeof LayoutTechniqueMaintenanceSettingsRoute
  '/_layout/technique/predictive': typeof LayoutTechniquePredictiveRoute
  '/_layout/technique/security': typeof LayoutTechniqueSecurityRoute
  '/_layout/technique/spare-parts': typeof LayoutTechniqueSparePartsRoute
  '/_layout/technique/technicians': typeof LayoutTechniqueTechniciansRoute
  '/_layout/technique/work-orders': typeof LayoutTechniqueWorkOrdersRoute
  '/_layout/technique/': typeof LayoutTechniqueIndexRoute
  '/_layout/technique/equipment/$equipmentId': typeof LayoutTechniqueEquipmentEquipmentIdRoute
  '/_layout/technique/equipment/new': typeof LayoutTechniqueEquipmentNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/technique'
    | '/admin'
    | '/assistant'
    | '/control-tower'
    | '/dashboard'
    | '/inbound-orders'
    | '/items'
    | '/outbound-orders'
    | '/settings'
    | '/shipment'
    | '/shipped'
    | '/warehouse'
    | '/warehouse-3d'
    | '/warehouse-3d-help'
    | '/warehouse-simulation'
    | '/warehouse-tasks'
    | '/warehouse-twin'
    | '/technique/alerts'
    | '/technique/analytics'
    | '/technique/integrations'
    | '/technique/maintenance'
    | '/technique/maintenance-schedule'
    | '/technique/maintenance-settings'
    | '/technique/predictive'
    | '/technique/security'
    | '/technique/spare-parts'
    | '/technique/technicians'
    | '/technique/work-orders'
    | '/technique/'
    | '/technique/equipment/$equipmentId'
    | '/technique/equipment/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/assistant'
    | '/control-tower'
    | '/dashboard'
    | '/inbound-orders'
    | '/items'
    | '/outbound-orders'
    | '/settings'
    | '/shipment'
    | '/shipped'
    | '/warehouse'
    | '/warehouse-3d'
    | '/warehouse-3d-help'
    | '/warehouse-simulation'
    | '/warehouse-tasks'
    | '/warehouse-twin'
    | '/'
    | '/technique/alerts'
    | '/technique/analytics'
    | '/technique/integrations'
    | '/technique/maintenance'
    | '/technique/maintenance-schedule'
    | '/technique/maintenance-settings'
    | '/technique/predictive'
    | '/technique/security'
    | '/technique/spare-parts'
    | '/technique/technicians'
    | '/technique/work-orders'
    | '/technique'
    | '/technique/equipment/$equipmentId'
    | '/technique/equipment/new'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/technique'
    | '/_layout/admin'
    | '/_layout/assistant'
    | '/_layout/control-tower'
    | '/_layout/dashboard'
    | '/_layout/inbound-orders'
    | '/_layout/items'
    | '/_layout/outbound-orders'
    | '/_layout/settings'
    | '/_layout/shipment'
    | '/_layout/shipped'
    | '/_layout/warehouse'
    | '/_layout/warehouse-3d'
    | '/_layout/warehouse-3d-help'
    | '/_layout/warehouse-simulation'
    | '/_layout/warehouse-tasks'
    | '/_layout/warehouse-twin'
    | '/_layout/'
    | '/_layout/technique/alerts'
    | '/_layout/technique/analytics'
    | '/_layout/technique/integrations'
    | '/_layout/technique/maintenance'
    | '/_layout/technique/maintenance-schedule'
    | '/_layout/technique/maintenance-settings'
    | '/_layout/technique/predictive'
    | '/_layout/technique/security'
    | '/_layout/technique/spare-parts'
    | '/_layout/technique/technicians'
    | '/_layout/technique/work-orders'
    | '/_layout/technique/'
    | '/_layout/technique/equipment/$equipmentId'
    | '/_layout/technique/equipment/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/warehouse-twin': {
      id: '/_layout/warehouse-twin'
      path: '/warehouse-twin'
      fullPath: '/warehouse-twin'
      preLoaderRoute: typeof LayoutWarehouseTwinRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/warehouse-tasks': {
      id: '/_layout/warehouse-tasks'
      path: '/warehouse-tasks'
      fullPath: '/warehouse-tasks'
      preLoaderRoute: typeof LayoutWarehouseTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/warehouse-simulation': {
      id: '/_layout/warehouse-simulation'
      path: '/warehouse-simulation'
      fullPath: '/warehouse-simulation'
      preLoaderRoute: typeof LayoutWarehouseSimulationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/warehouse-3d-help': {
      id: '/_layout/warehouse-3d-help'
      path: '/warehouse-3d-help'
      fullPath: '/warehouse-3d-help'
      preLoaderRoute: typeof LayoutWarehouse3dHelpRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/warehouse-3d': {
      id: '/_layout/warehouse-3d'
      path: '/warehouse-3d'
      fullPath: '/warehouse-3d'
      preLoaderRoute: typeof LayoutWarehouse3dRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/warehouse': {
      id: '/_layout/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof LayoutWarehouseRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shipped': {
      id: '/_layout/shipped'
      path: '/shipped'
      fullPath: '/shipped'
      preLoaderRoute: typeof LayoutShippedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shipment': {
      id: '/_layout/shipment'
      path: '/shipment'
      fullPath: '/shipment'
      preLoaderRoute: typeof LayoutShipmentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/outbound-orders': {
      id: '/_layout/outbound-orders'
      path: '/outbound-orders'
      fullPath: '/outbound-orders'
      preLoaderRoute: typeof LayoutOutboundOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inbound-orders': {
      id: '/_layout/inbound-orders'
      path: '/inbound-orders'
      fullPath: '/inbound-orders'
      preLoaderRoute: typeof LayoutInboundOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/control-tower': {
      id: '/_layout/control-tower'
      path: '/control-tower'
      fullPath: '/control-tower'
      preLoaderRoute: typeof LayoutControlTowerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/assistant': {
      id: '/_layout/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof LayoutAssistantRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/technique': {
      id: '/_layout/technique'
      path: '/technique'
      fullPath: '/technique'
      preLoaderRoute: typeof LayoutTechniqueRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/technique/': {
      id: '/_layout/technique/'
      path: '/'
      fullPath: '/technique/'
      preLoaderRoute: typeof LayoutTechniqueIndexRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
    '/_layout/technique/work-orders': {
      id: '/_layout/technique/work-orders'
      path: '/work-orders'
      fullPath: '/technique/work-orders'
      preLoaderRoute: typeof LayoutTechniqueWorkOrdersRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
    '/_layout/technique/technicians': {
      id: '/_layout/technique/technicians'
      path: '/technicians'
      fullPath: '/technique/technicians'
      preLoaderRoute: typeof LayoutTechniqueTechniciansRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
    '/_layout/technique/spare-parts': {
      id: '/_layout/technique/spare-parts'
      path: '/spare-parts'
      fullPath: '/technique/spare-parts'
      preLoaderRoute: typeof LayoutTechniqueSparePartsRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
    '/_layout/technique/security': {
      id: '/_layout/technique/security'
      path: '/security'
      fullPath: '/technique/security'
      preLoaderRoute: typeof LayoutTechniqueSecurityRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
    '/_layout/technique/predictive': {
      id: '/_layout/technique/predictive'
      path: '/predictive'
      fullPath: '/technique/predictive'
      preLoaderRoute: typeof LayoutTechniquePredictiveRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
    '/_layout/technique/maintenance-settings': {
      id: '/_layout/technique/maintenance-settings'
      path: '/maintenance-settings'
      fullPath: '/technique/maintenance-settings'
      preLoaderRoute: typeof LayoutTechniqueMaintenanceSettingsRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
    '/_layout/technique/maintenance-schedule': {
      id: '/_layout/technique/maintenance-schedule'
      path: '/maintenance-schedule'
      fullPath: '/technique/maintenance-schedule'
      preLoaderRoute: typeof LayoutTechniqueMaintenanceScheduleRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
    '/_layout/technique/maintenance': {
      id: '/_layout/technique/maintenance'
      path: '/maintenance'
      fullPath: '/technique/maintenance'
      preLoaderRoute: typeof LayoutTechniqueMaintenanceRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
    '/_layout/technique/integrations': {
      id: '/_layout/technique/integrations'
      path: '/integrations'
      fullPath: '/technique/integrations'
      preLoaderRoute: typeof LayoutTechniqueIntegrationsRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
    '/_layout/technique/analytics': {
      id: '/_layout/technique/analytics'
      path: '/analytics'
      fullPath: '/technique/analytics'
      preLoaderRoute: typeof LayoutTechniqueAnalyticsRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
    '/_layout/technique/alerts': {
      id: '/_layout/technique/alerts'
      path: '/alerts'
      fullPath: '/technique/alerts'
      preLoaderRoute: typeof LayoutTechniqueAlertsRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
    '/_layout/technique/equipment/new': {
      id: '/_layout/technique/equipment/new'
      path: '/equipment/new'
      fullPath: '/technique/equipment/new'
      preLoaderRoute: typeof LayoutTechniqueEquipmentNewRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
    '/_layout/technique/equipment/$equipmentId': {
      id: '/_layout/technique/equipment/$equipmentId'
      path: '/equipment/$equipmentId'
      fullPath: '/technique/equipment/$equipmentId'
      preLoaderRoute: typeof LayoutTechniqueEquipmentEquipmentIdRouteImport
      parentRoute: typeof LayoutTechniqueRouteRoute
    }
  }
}

interface LayoutTechniqueRouteRouteChildren {
  LayoutTechniqueAlertsRoute: typeof LayoutTechniqueAlertsRoute
  LayoutTechniqueAnalyticsRoute: typeof LayoutTechniqueAnalyticsRoute
  LayoutTechniqueIntegrationsRoute: typeof LayoutTechniqueIntegrationsRoute
  LayoutTechniqueMaintenanceRoute: typeof LayoutTechniqueMaintenanceRoute
  LayoutTechniqueMaintenanceScheduleRoute: typeof LayoutTechniqueMaintenanceScheduleRoute
  LayoutTechniqueMaintenanceSettingsRoute: typeof LayoutTechniqueMaintenanceSettingsRoute
  LayoutTechniquePredictiveRoute: typeof LayoutTechniquePredictiveRoute
  LayoutTechniqueSecurityRoute: typeof LayoutTechniqueSecurityRoute
  LayoutTechniqueSparePartsRoute: typeof LayoutTechniqueSparePartsRoute
  LayoutTechniqueTechniciansRoute: typeof LayoutTechniqueTechniciansRoute
  LayoutTechniqueWorkOrdersRoute: typeof LayoutTechniqueWorkOrdersRoute
  LayoutTechniqueIndexRoute: typeof LayoutTechniqueIndexRoute
  LayoutTechniqueEquipmentEquipmentIdRoute: typeof LayoutTechniqueEquipmentEquipmentIdRoute
  LayoutTechniqueEquipmentNewRoute: typeof LayoutTechniqueEquipmentNewRoute
}

const LayoutTechniqueRouteRouteChildren: LayoutTechniqueRouteRouteChildren = {
  LayoutTechniqueAlertsRoute: LayoutTechniqueAlertsRoute,
  LayoutTechniqueAnalyticsRoute: LayoutTechniqueAnalyticsRoute,
  LayoutTechniqueIntegrationsRoute: LayoutTechniqueIntegrationsRoute,
  LayoutTechniqueMaintenanceRoute: LayoutTechniqueMaintenanceRoute,
  LayoutTechniqueMaintenanceScheduleRoute:
    LayoutTechniqueMaintenanceScheduleRoute,
  LayoutTechniqueMaintenanceSettingsRoute:
    LayoutTechniqueMaintenanceSettingsRoute,
  LayoutTechniquePredictiveRoute: LayoutTechniquePredictiveRoute,
  LayoutTechniqueSecurityRoute: LayoutTechniqueSecurityRoute,
  LayoutTechniqueSparePartsRoute: LayoutTechniqueSparePartsRoute,
  LayoutTechniqueTechniciansRoute: LayoutTechniqueTechniciansRoute,
  LayoutTechniqueWorkOrdersRoute: LayoutTechniqueWorkOrdersRoute,
  LayoutTechniqueIndexRoute: LayoutTechniqueIndexRoute,
  LayoutTechniqueEquipmentEquipmentIdRoute:
    LayoutTechniqueEquipmentEquipmentIdRoute,
  LayoutTechniqueEquipmentNewRoute: LayoutTechniqueEquipmentNewRoute,
}

const LayoutTechniqueRouteRouteWithChildren =
  LayoutTechniqueRouteRoute._addFileChildren(LayoutTechniqueRouteRouteChildren)

interface LayoutRouteChildren {
  LayoutTechniqueRouteRoute: typeof LayoutTechniqueRouteRouteWithChildren
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAssistantRoute: typeof LayoutAssistantRoute
  LayoutControlTowerRoute: typeof LayoutControlTowerRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutInboundOrdersRoute: typeof LayoutInboundOrdersRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutOutboundOrdersRoute: typeof LayoutOutboundOrdersRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutShipmentRoute: typeof LayoutShipmentRoute
  LayoutShippedRoute: typeof LayoutShippedRoute
  LayoutWarehouseRoute: typeof LayoutWarehouseRoute
  LayoutWarehouse3dRoute: typeof LayoutWarehouse3dRoute
  LayoutWarehouse3dHelpRoute: typeof LayoutWarehouse3dHelpRoute
  LayoutWarehouseSimulationRoute: typeof LayoutWarehouseSimulationRoute
  LayoutWarehouseTasksRoute: typeof LayoutWarehouseTasksRoute
  LayoutWarehouseTwinRoute: typeof LayoutWarehouseTwinRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutTechniqueRouteRoute: LayoutTechniqueRouteRouteWithChildren,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAssistantRoute: LayoutAssistantRoute,
  LayoutControlTowerRoute: LayoutControlTowerRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutInboundOrdersRoute: LayoutInboundOrdersRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutOutboundOrdersRoute: LayoutOutboundOrdersRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutShipmentRoute: LayoutShipmentRoute,
  LayoutShippedRoute: LayoutShippedRoute,
  LayoutWarehouseRoute: LayoutWarehouseRoute,
  LayoutWarehouse3dRoute: LayoutWarehouse3dRoute,
  LayoutWarehouse3dHelpRoute: LayoutWarehouse3dHelpRoute,
  LayoutWarehouseSimulationRoute: LayoutWarehouseSimulationRoute,
  LayoutWarehouseTasksRoute: LayoutWarehouseTasksRoute,
  LayoutWarehouseTwinRoute: LayoutWarehouseTwinRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
